version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/devops
    
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run: 
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=env* --statistics
            pytest --junitxml=test-results/junit.xml
      
      - store_test_results: 
          path: test-results

      - store_artifacts:
          path: test-results

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main

