# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/devops  # Corrected indentation
    
    steps:
      # 1. obtain repo from git
      - checkout
      # 2. create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      - run: 
          # run coding convention software and test   
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=env* --statistics
            pytest --junitxml=test-results/junit.xml
      
      - store_test_results: 
          path: test-results

      - store_artifacts:
          path: test-results
